name: 'Setup Python + uv environment'
description: 'Setup Python + uv environment'

inputs:
  python-version:
    required: false
    description: 'Python version'
    default: '3.11'
outputs: {}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{inputs.python-version}}
    - name: Install uv
      run: python -m pip install uv
      shell: bash
    - name: Create virtual environment and install dependencies
      run: uv sync --all-groups
      shell: bash
    - name: Install jaxlib
      run: uv pip install --upgrade "jax[cpu]"
      shell: bash
