name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: astanziola/action_update_python_project@v9
        with:
          python-version: "3.11"
          test-script: |
            uv run --no-sync python -c "import jaxdf; print(jaxdf.__version__)"
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          github-user: ucl-bug
          github-token: ${{ github.token }}
