name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: astanziola/action_update_python_project@v9
        with:
          python-version: "3.11"
          test-script: |
            uv run --no-sync python -c "import jaxdf; print(jaxdf.__version__)"
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          github-user: ucl-bug
          github-token: ${{ github.token }}

  docs:
    runs-on: ubuntu-latest
    needs: release
    if: success()
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-uv-env
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
